#ifndef INSERTION_MODE_H_
#define INSERTION_MODE_H_

#ifdef __cplusplus
extern "C"{
#endif

typedef enum {
    INSERTION_MODE_INITIAL,
    INSERTION_MODE_BEFORE_HTML,
    INSERTION_MODE_BEFORE_HEAD,
    INSERTION_MODE_IN_HEAD,
    INSERTION_MODE_IN_HEAD_NOSCRIPT,
    INSERTION_MODE_AFTER_HEAD,
    INSERTION_MODE_IN_BODY,
    INSERTION_MODE_TEXT,
    INSERTION_MODE_IN_TABLE,
    INSERTION_MODE_IN_TABLE_TEXT,
    INSERTION_MODE_IN_CAPTION,
    INSERTION_MODE_IN_COLUMN_GROUP,
    INSERTION_MODE_IN_TABLE_BODY,
    INSERTION_MODE_IN_ROW,
    INSERTION_MODE_IN_CELL,
    INSERTION_MODE_IN_SELECT,
    INSERTION_MODE_IN_SELECT_IN_TABLE,
    INSERTION_MODE_AFTER_BODY,
    INSERTION_MODE_IN_FRAMESET,
    INSERTION_MODE_AFTER_FRAMESET,
    INSERTION_MODE_AFTER_AFTER_BODY,
    INSERTION_MODE_AFTER_AFTER_FRAMESET
}InsertionMode;

#ifdef __cplusplus
}
#endif

#endif // INSERTION_MODE_H_
